/*
 * Created by biatekjt on Mar 29, 2010
 *
 * University of Minnesota, Morris
 * http://www.morris.umn.edu/
 */
package umm.digiquilt.xmlsaveload;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

import umm.digiquilt.model.Challenge;
import umm.digiquilt.xmlsaveload.handlers.ChallengeFileHandler;

/**
 * Parses a challenge file.
 * 
 * @author Jason Biatek, last changed by $Author: lamberty $
 * on $Date: 2008/01/22 17:50:24 $
 * @version $Revision: 1.1 $
 *
 */
public class ChallengeFileParser {
    
    /**
     * The handler which does the actual parsing for us.
     */
    ChallengeFileHandler handler;

    /**
     * @param inputStream 
     * @throws SAXException 
     * @throws IOException 
     */
    public ChallengeFileParser(InputStream inputStream) throws SAXException, IOException {
        XMLReader xmlReader = XMLReaderFactory.createXMLReader();
        handler = new ChallengeFileHandler(xmlReader);
        
        xmlReader.setContentHandler(handler);
        xmlReader.setErrorHandler(handler);
        
        xmlReader.parse(new InputSource(inputStream));
    }

    /**
     * @return the list of challenges generated by the handler.
     */
    public List<Challenge> getChallenges() {
        return handler.getChallenges();
    }

}
